### ISSUE TITLE
Install method fails on Ubuntu

### ISSUE THREAD

**Issue by ripefig** [OneAdder/libinput_gestures_qt#1]
Upon launching the application:

```
Traceback (most recent call last):
  File "/usr/local/bin/libinput-gestures-qt", line 2, in <module>
    from libinput_gestures_qt.main import main
ModuleNotFoundError: No module named 'libinput_gestures_qt'

```

**Comment by OneAdder** [comment]
Try installing `setuptools-git` and tell me if it works. I will think about imports now (it's a bit spaghetty)

**Comment by OneAdder** [comment]
BTW: could you find it under `/usr/local/lib/python3.7/site-packages/` and tell me what files and directories are there?

**Comment by OneAdder** [comment]
I deleted lines that forced to install into `/usr/local/.../libinput-gestures-qt`. Now it is installed to either `/usr/share/...` or `/usr/local/share/...`. Probably, it should help

**Comment by ripefig** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/libinput-gestures-qt", line 4, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/libinput_gestures_qt/main.py", line 786, in main
    window = GesturesApp()
  File "/usr/local/lib/python3.6/dist-packages/libinput_gestures_qt/main.py", line 287, in __init__
    self.QDBUS_NAME = get_qdbus_name()
  File "/usr/local/lib/python3.6/dist-packages/libinput_gestures_qt/main.py", line 261, in get_qdbus_name
    subprocess.run('qdbus', capture_output=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by OneAdder** [comment]
Well, that's a bit weird because `Python 3.7.3` version seems to understand my synthax...  
Nevertheless, I pushed a fix for this problem. Could you check if it works on your system?  
And thank you for your feedback! You are one of the first people testing it :)

**Comment by ripefig** [comment]
The same error persists. However I have python 3.6.7.

**Comment by OneAdder** [comment]
I inspected the docs for `3.6`.`capture_output` is `3.7` exclusive feature.
I found a way to emulate the behavior of `capture_output` with old features, but I don't want to mess my master with legacy support code. I will create a separate branch for older python versions

**Comment by OneAdder** [comment]
Done. Now you can try it. You can switch to `git checkout legacy_python`  
It seems to be working. But I don't really plan to support it well.

**Comment by joystein** [comment]
I have made a pull request (#2 ) for <3.7 support. This change tries to minimize the effect of supporting versions older than 3.7. I also wonder if it is a bit premature to declare py3.6 legacy since it is [supported until 2021](https://www.python.org/dev/peps/pep-0494/#id12). Python 3.6 is also the py3 version on the latest ubuntu lts.

**Comment by OneAdder** [comment]
Agreed. Thank you for your pull request
